// Shared course options for student forms
export const COURSE_OPTIONS = [
  "Doctor of Philosophy in Animal Science",
  "Doctor of Philosophy in Crop Science",
  "Doctor of Philosophy in Education",
  "Doctor of Public Administration",
  "Doctor of Philosophy in Resource Management",
  "Master of Arts in Education",
  "Master of Arts in Teaching Livelihood Education",
  "Master of Science Major in Mathematics Education, Biology Education and Chemistry Education",
  "Master of Science in Animal Science",
  "Master of Science in Crop Science",
  "Master of Science in Agricultural Engineering",
  "Master in Business Administration",
  "Master in Public Administration",
  "Master of Arts in Psychology",
  "Master of Arts in English",
  "Master in Chemistry",
  "Master in Mathematics",
  "Master of Biology",
  "Master in Psychology",
  "Master in Information Technology",
  "Doctor of Veterinary Medicine",
  "Bachelor of Science in Animal Husbandry",
  "Bachelor of Science in Agriculture",
  "Bachelor of Science in Agribusiness",
  "Bachelor of Science in Forestry",
  "Bachelor of Science in Environmental Science",
  "Bachelor of Science in Biology",
  "Bachelor of Science in Mathematics",
  "Bachelor of Science in Chemistry",
  "Bachelor of Science in Psychology",
  "Bachelor of Arts in Communication",
  "Bachelor of Arts in English Language Studies",
  "B.S. in Business Administration",
  "Bachelor in Public Administration",
  "B.S. in Management Accounting",
  "B.S. in Entrepreneurship",
  "B.S. in Accountancy",
  "B.S. in Hospitality Management",
  "B.S. in Tourism Management",
  "Bachelor of Science in Agricultural and Biosystems Engineering",
  "B.S. in Civil Engineering",
  "Bachelor of Elementary Education",
  "Bachelor of Secondary Education",
  "Bachelor of Physical Education",
  "Bachelor of Technology and Livelihood Education",
  "Bachelor of Science in Information Technology",
  "Bachelor of Science in Information Systems",
  "Bachelor of Science in Computer Science",
  "Bachelor of Library and Information Science",
  "B.S. in Fisheries and Aquatic Sciences",
  "B.S. in Criminology",
  "Bachelor of Science in Law Enforcement Administration",
  "Bachelor of Science in Nursing",
  "3 Year Diploma in Agricultural Technology",
];
